# Generated by Django 3.1.5 on 2021-01-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=70)),
                ('tweet', models.CharField(blank=True, default='', max_length=200)),
                ('retweet_count', models.CharField(blank=True, default='', max_length=200)),
                ('place', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.CharField(blank=True, default='', max_length=40)),
            ],
        ),
    ]
