# Generated by Django 3.1.5 on 2021-02-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='tweet',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
